// FETCH BOOK
export const GET_BOOK_START = 'GET_BOOK_START';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_BOOK_FAIL = 'GET_BOOK_FAIL';

// FETCH BOOKS
export const GET_BOOKS_START = 'GET_BOOKS_START';
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const GET_BOOKS_FAIL = 'GET_BOOKS_FAIL';

// FETCH NEW BOOKS
export const GET_NEW_BOOKS_START = 'GET_NEW_BOOKS_START';
export const GET_NEW_BOOKS_SUCCESS = 'GET_NEW_BOOKS_SUCCESS';
export const GET_NEW_BOOKS_FAIL = 'GET_NEW_BOOKS_FAIL';

// UPDATE BOOK
export const UPDATE_BOOK_START = 'UPDATE_BOOK_START';
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
export const UPDATE_BOOK_FAIL = 'UPDATE_BOOK_FAIL';

// CREATE BOOK
export const CREATE_BOOK_START = 'CREATE_BOOK_START';
export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
export const CREATE_BOOK_FAIL = 'CREATE_BOOK_FAIL';

// SEARCH IN BOOKS
export const SEARCH_BOOKS_START = 'SEARCH_BOOKS_START';
export const SEARCH_BOOKS_SUCCESS = 'SEARCH_BOOKS_SUCCESS';
export const SEARCH_BOOKS_FAIL = 'SEARCH_BOOKS_FAIL';

// FIND RECOMMENDED BOOKS
export const RECOMMENDED_BOOKS_START = 'RECOMMENDED_BOOKS_START';
export const RECOMMENDED_BOOKS_SUCCESS = 'RECOMMENDED_BOOKS_SUCCESS';
export const RECOMMENDED_BOOKS_FAIL = 'RECOMMENDED_BOOKS_FAIL';
